# Site settings
title: 朱益锋的博客
name: 朱益锋的博客
email: 994613212@qq.com
author: 朱益锋
url: 
github: https://github.com/zyfilife/
baseurl: ""
description: iOS开发随笔
meta_description: 康志华;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: iOS开发随笔
banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

# exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: zyfilife

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    line_numbers: false
    css_class: 'codehilite'
    default_lang: java
    block: 
      line_numbers: false

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/zyfilife.github.com/